<?php

namespace Database\Seeders;

use App\Models\Course;
use Illuminate\Database\Seeder;

class CourseSeeder extends Seeder
{
    public function run(): void
    {
        $courses = [
            [
                'slug'              => 'noorani-qaida',
                'title'             => 'Noorani Qaida',
                'short_description' => 'Start from the very beginning — Arabic letters, pronunciation, and Qaida rules.',
                'long_description'  => 'The perfect entry point for anyone new to Arabic and Quran. Learn the Arabic alphabet, letter forms, vowel marks, and basic recitation rules through the proven Noorani Qaida methodology.',
                'icon'              => 'BookOpen',
                'age_group'         => null,
                'level'             => 'Beginner',
                'duration_months'   => '2–4',
                'features'          => ['Arabic alphabet mastery', 'Correct pronunciation from day one', 'Vowel marks (harakat)', 'Foundation for Tajweed'],
                'seo_title'         => 'Noorani Qaida Online Course | Azhary',
                'seo_description'   => 'Learn to read Arabic and Quran from scratch with Noorani Qaida. 1-on-1 certified teacher. Free trial class. Students in 50+ countries.',
                'outcomes'          => ['Read all 29 Arabic letters in isolation and connected form', 'Pronounce every letter from its correct articulation point (Makharij)', 'Apply short vowels, tanween, sukoon, and shaddah correctly', 'Recite with natural Madd (elongation) rules', 'Complete the full Noorani Qaida with teacher assessment'],
                'curriculum'        => [
                    ['module' => 'Lesson 1–7: Arabic Alphabet', 'topics' => ['All 29 letters in isolation', 'Recognizing letter forms — initial, medial, final', 'Articulation points (Makharij al-Huroof)']],
                    ['module' => 'Lesson 8–14: Short Vowels (Harakaat)', 'topics' => ['Fatha, Kasra, Dhamma', 'Tanween (nunation) — three forms', 'Sukoon and shaddah']],
                    ['module' => 'Lesson 15–20: Madd (Elongation)', 'topics' => ['Natural Madd — Alif, Waw, Ya', 'Madd Al-Leen', 'Identifying Madd in real words']],
                    ['module' => 'Lesson 21–26: Joining Letters', 'topics' => ['Reading two-letter combinations', 'Three- and four-letter words', 'Common patterns in Quranic words']],
                    ['module' => 'Lesson 27–32: Quran Verses Practice', 'topics' => ['Short surahs with full Tajweed', 'Fluency and speed drills', 'Teacher assessment and completion certificate']],
                ],
                'personas'          => [
                    ['title' => 'Complete Beginners', 'description' => 'You have never read Arabic and want to start from the very first letter. No prior knowledge required.'],
                    ['title' => 'Parents of Young Children', 'description' => 'Your child is aged 4–12 and ready to begin their Quran journey. Our teachers specialize in engaging young learners.'],
                    ['title' => 'Reverts to Islam', 'description' => "You're new to Islam and want to learn the Quran properly from the beginning — with patience and no judgment."],
                ],
                'faqs'              => [
                    ['q' => 'How long does it take to complete the Noorani Qaida?', 'a' => 'Most students complete it in 2–4 months with 3 sessions per week. Children may take slightly longer based on age and consistency.'],
                    ['q' => 'Do I need any Arabic knowledge before starting?', 'a' => 'None at all. The course begins with the very first letter and builds step by step.'],
                    ['q' => 'Is it suitable for children?', 'a' => 'Yes — we teach students as young as 4. Our teachers are experienced with children and use engaging, patient methods.'],
                    ['q' => 'What comes after finishing the Noorani Qaida?', 'a' => 'You move directly into Quran reading with Tajweed. Your teacher will guide the transition based on your level.'],
                    ['q' => 'How are sessions held?', 'a' => 'All classes are 1-on-1 via video call (Zoom or Google Meet), scheduled at times convenient for you.'],
                    ['q' => 'Is there a certificate upon completion?', 'a' => 'Yes — your teacher assesses your proficiency at the end and issues a completion certificate.'],
                ],
                'related_slugs'    => ['quran-classes-for-kids', 'tajweed-course', 'quran-classes-for-adults'],
                'specialty_tags'   => ['Noorani Qaida', 'Quran for Kids', 'Tajweed'],
                'sort_order'       => 1,
            ],
            [
                'slug'              => 'quran-classes-for-kids',
                'title'             => 'Quran for Kids',
                'short_description' => 'Fun, structured Quran learning designed for children aged 5 to 14.',
                'long_description'  => "Our children's program combines the Noorani Qaida, Tajweed basics, and age-appropriate Islamic values in a fun, encouraging environment. Teachers are certified and experienced with young learners.",
                'icon'              => 'Star',
                'age_group'         => 'Ages 5–14',
                'level'             => 'Beginner',
                'duration_months'   => null,
                'features'          => ['Noorani Qaida included', 'Patient, child-specialist teachers', 'Interactive and engaging lessons', 'Progress reports for parents'],
                'seo_title'         => 'Online Quran Classes for Kids | Ages 5–14 | Azhary',
                'seo_description'   => 'Fun, structured online Quran classes for children aged 5–14. Certified child-specialist teachers. Free trial class. Join families from 50+ countries.',
                'outcomes'          => ['Complete the Noorani Qaida and begin Quran reading', 'Recite short surahs with basic Tajweed', 'Understand the meaning of Surah Al-Fatiha and key duas', 'Develop love and respect for the Quran from an early age', 'Build a consistent Quran habit with structured teacher support'],
                'curriculum'        => [
                    ['module' => 'Noorani Qaida Foundation', 'topics' => ['Arabic alphabet and letter forms', 'Vowels, sukoon, and tanween', 'Word-joining exercises']],
                    ['module' => 'Quran Reading Basics', 'topics' => ['Reading short surahs — Fatiha through An-Nas', 'Tajweed basics: Madd, Ghunna, Qalqala', 'Pronunciation practice with teacher']],
                    ['module' => 'Memorization of Short Surahs', 'topics' => ['Surahs Al-Ikhlas, Al-Falaq, An-Nas', 'Surah Al-Fatiha and daily prayer surahs', 'Review and retention techniques']],
                    ['module' => 'Islamic Values & Duas', 'topics' => ['Meaning of key surahs in simple language', 'Daily duas — before eating, sleeping, etc.', 'Basic aqeedah for children']],
                    ['module' => 'Progress & Parent Reports', 'topics' => ['Monthly progress assessments', 'Teacher feedback reports for parents', 'Goal-setting for next milestone']],
                ],
                'personas'          => [
                    ['title' => 'Parents of Children Ages 5–8', 'description' => 'Your child is ready to start learning Arabic letters and basic Quran reading in a fun, nurturing environment.'],
                    ['title' => 'Parents of Children Ages 9–14', 'description' => 'Your child can already read a bit but needs structured Tajweed and regular practice with a qualified teacher.'],
                    ['title' => 'Families Seeking Islamic Education', 'description' => 'You want your child to grow up connected to the Quran with both correct recitation and basic Islamic understanding.'],
                ],
                'faqs'              => [
                    ['q' => 'What age can my child start?', 'a' => 'We accept students from age 4–5. For very young children, we recommend starting with just 2 short sessions of 30 minutes per week.'],
                    ['q' => 'Are your teachers experienced with children?', 'a' => "Yes. All teachers in our children's program have specialized training in child-friendly learning methods and are patient, encouraging, and experienced."],
                    ['q' => 'How long is each session for children?', 'a' => "We recommend 30 minutes for ages 5–7 and 45 minutes for ages 8 and above. Sessions are flexible based on your child's attention span."],
                    ['q' => "Will I receive updates on my child's progress?", 'a' => 'Yes — teachers send monthly progress reports. You can also attend a class at any time to observe.'],
                    ['q' => 'Do you have female teachers for girls?', 'a' => 'Absolutely. We have a team of certified female teachers and can always match your daughter with a female teacher upon request.'],
                    ['q' => 'What if my child already knows some Arabic?', 'a' => 'We assess every student before their first paid class and place them at the right level. No student repeats material they already know.'],
                ],
                'related_slugs'    => ['noorani-qaida', 'hifz-memorization', 'islamic-studies'],
                'specialty_tags'   => ['Quran for Kids', 'Noorani Qaida', 'Islamic Studies for Kids'],
                'sort_order'       => 2,
            ],
            [
                'slug'              => 'quran-classes-for-adults',
                'title'             => 'Quran for Adults',
                'short_description' => 'Start or restart your Quran journey as an adult — at your own pace, with your own teacher.',
                'long_description'  => 'Designed for adults who are beginners or returning to the Quran after a gap. No judgment, no rush — just a qualified teacher dedicated entirely to your progress. Covers Noorani Qaida through Tajweed at a pace that works for your life.',
                'icon'              => 'BookOpen',
                'age_group'         => 'Adults 18+',
                'level'             => 'Beginner',
                'duration_months'   => null,
                'features'          => ['Start from scratch or pick up where you left off', 'Flexible scheduling around work and family', 'Certified teacher, 1-on-1 only', 'Tajweed correction from the first lesson'],
                'seo_title'         => 'Online Quran Classes for Adults | Azhary',
                'seo_description'   => 'Start or restart your Quran journey as an adult. 1-on-1 classes at your pace with certified teachers. Free first class. No prior knowledge needed.',
                'outcomes'          => ['Read the Quran independently with correct pronunciation', 'Apply core Tajweed rules from the first lesson', 'Complete Noorani Qaida if starting from scratch', 'Build a consistent Quran reading habit', 'Recite Surah Al-Fatiha and common prayer surahs perfectly'],
                'curriculum'        => [
                    ['module' => 'Assessment & Placement', 'topics' => ['Level test with your teacher', 'Tailored curriculum based on your current level', 'Setting realistic goals and milestones']],
                    ['module' => 'Arabic Alphabet & Pronunciation', 'topics' => ['All 29 letters from articulation points', 'Common pronunciation errors corrected', 'Connecting letters in words']],
                    ['module' => 'Vowels, Sukoon & Tanween', 'topics' => ['Short and long vowels (Harakaat)', 'Sukoon and shaddah rules', 'Tanween and its pronunciation']],
                    ['module' => 'Quran Reading with Basic Tajweed', 'topics' => ['Juz Amma — short surahs read with rules', 'Madd rules in context', 'Ghunna, Qalqala, and Idghaam basics']],
                    ['module' => 'Independent Quran Fluency', 'topics' => ['Reading longer passages independently', 'Self-correction techniques', 'Teacher evaluation and next steps']],
                ],
                'personas'          => [
                    ['title' => 'Adults Who Never Learned', 'description' => "You grew up without Quran education and feel it's time to start. No shame, no rush — just a qualified teacher dedicated to your progress."],
                    ['title' => 'Lapsed Students Returning', 'description' => "You learned as a child but haven't practiced in years. We'll pick up where you left off without wasting your time on basics you already know."],
                    ['title' => 'Reverts to Islam', 'description' => "You're new to Islam and want to connect with the Quran. Our teachers are experienced, non-judgmental, and supportive."],
                ],
                'faqs'              => [
                    ['q' => "I'm an adult beginner — is it too late to start?", 'a' => "It's never too late. Many of our students start in their 40s, 50s, and even 60s and successfully learn to read the Quran beautifully."],
                    ['q' => 'Do you have evening or weekend slots?', 'a' => 'Yes — we have teachers available 7 days a week across all major timezones, with early morning, evening, and weekend slots.'],
                    ['q' => 'Will I be judged for not knowing anything?', 'a' => 'Never. Our teachers are trained to work with adults at all levels, including those starting from zero. We create a safe, patient learning environment.'],
                    ['q' => 'How many classes per week do you recommend?', 'a' => 'We recommend 3 classes per week (30–45 minutes each) for steady progress. You can adjust based on your schedule and goals.'],
                    ['q' => 'Is there a difference between this course and the Tajweed course?', 'a' => 'The adult Quran course covers reading from scratch through basic Tajweed. The dedicated Tajweed course goes deeper into all Tajweed rules for students who can already read fluently.'],
                    ['q' => 'Can I switch teachers if I want?', 'a' => 'Yes — if you feel the learning style is not the right fit, we will match you with another teacher with no questions asked.'],
                ],
                'related_slugs'    => ['noorani-qaida', 'tajweed-course', 'female-quran-teachers'],
                'specialty_tags'   => ['Quran for Adults', 'Tajweed', 'Noorani Qaida'],
                'sort_order'       => 3,
            ],
            [
                'slug'              => 'tajweed-course',
                'title'             => 'Tajweed Course',
                'short_description' => 'Master the rules of Tajweed and recite the Quran beautifully and correctly.',
                'long_description'  => 'Tajweed is the science of reciting the Quran the way it was revealed — with proper pronunciation, elongation, and articulation. Our structured curriculum covers all Tajweed rules with practical application in Quran verses.',
                'icon'              => 'Mic',
                'age_group'         => null,
                'level'             => 'Beginner',
                'duration_months'   => '6–12',
                'features'          => ['All Tajweed rules covered', 'Real-time pronunciation correction', 'Practice with actual Quran verses', 'Certificate upon completion'],
                'seo_title'         => 'Online Tajweed Course | Master Quran Recitation | Azhary',
                'seo_description'   => 'Master all Tajweed rules with a certified teacher. Real-time pronunciation correction, Quran verse practice. Free trial. Students worldwide.',
                'outcomes'          => ['Understand and correctly apply all major Tajweed rules', 'Recite any Quranic passage with proper Tajweed', 'Identify and self-correct pronunciation errors', 'Receive a Tajweed completion certificate', 'Prepare for advanced Hifz or Ijazah programs'],
                'curriculum'        => [
                    ['module' => 'Makharij al-Huroof (Articulation Points)', 'topics' => ['Five regions of articulation', "Each letter's precise exit point", 'Common mispronunciation corrections']],
                    ['module' => 'Sifaat al-Huroof (Letter Characteristics)', 'topics' => ['Heavy vs. light letters — Tafkheem and Tarqeeq', 'Letters of Qalqala', 'Strong and weak characteristics']],
                    ['module' => 'Madd Rules (Elongation)', 'topics' => ["Madd Tabee'i — natural 2-count Madd", 'Madd Muttasil, Munfasil, and Aarid', 'Madd Al-Lazim and its types']],
                    ['module' => 'Noon Sakinah & Tanween Rules', 'topics' => ['Izhar — clear pronunciation', 'Idghaam — merging with and without Ghunna', 'Iqlab and Ikhfaa']],
                    ['module' => 'Meem Sakinah & Shaddah', 'topics' => ['Idghaam Shafawi', 'Ikhfaa Shafawi', 'Shaddah with elongation (Ghunna)']],
                    ['module' => 'Waqf & Ibtidaa (Stopping & Starting)', 'topics' => ['Types of Waqf marks in the Mushaf', 'Where to stop and start correctly', 'Applying Waqf rules in full recitation']],
                ],
                'personas'          => [
                    ['title' => 'Quran Readers Who Want Improvement', 'description' => 'You can read the Quran but know your Tajweed is not quite right. This course fixes that systematically.'],
                    ['title' => 'Students Preparing for Hifz or Ijazah', 'description' => 'Correct Tajweed is a prerequisite for both programs. This course prepares you for the next level.'],
                    ['title' => 'Adults Who Learned Incorrectly', 'description' => 'You were taught with some errors — perhaps informally or by a non-specialist. We rebuild the foundation correctly.'],
                ],
                'faqs'              => [
                    ['q' => 'Do I need to know how to read Quran before taking this course?', 'a' => 'Yes — this course is for students who can already read Arabic letters. If you are a complete beginner, start with our Noorani Qaida course first.'],
                    ['q' => 'How long does it take to complete the Tajweed course?', 'a' => 'Most students complete the full curriculum in 6–12 months with 3 sessions per week, depending on their starting level.'],
                    ['q' => 'Will I get a certificate?', 'a' => 'Yes — upon demonstrating proficiency in all Tajweed rules, your teacher will issue a Tajweed completion certificate.'],
                    ['q' => 'Can Tajweed be learned online?', 'a' => 'Absolutely. Our teachers provide real-time, live pronunciation correction via video call — just as effective as in-person, and often more efficient one-on-one.'],
                    ['q' => 'What is the difference between the Tajweed and Ijazah programs?', 'a' => 'Tajweed is the set of rules for correct recitation. Ijazah is a certified license granted after mastering Tajweed and being tested thoroughly — it is the next step after completing this course.'],
                ],
                'related_slugs'    => ['hifz-memorization', 'ijazah-program', 'ten-qiraat'],
                'specialty_tags'   => ['Tajweed', 'Ijazah', 'Ten Qiraat'],
                'sort_order'       => 4,
            ],
            [
                'slug'              => 'hifz-memorization',
                'title'             => 'Hifz / Memorization',
                'short_description' => 'Memorize the Quran with a structured curriculum and dedicated teacher support.',
                'long_description'  => 'Our Hifz program provides a structured, sustainable path to memorizing the entire Quran. Using proven memorization techniques, regular revision sessions, and one-on-one teacher support, we have helped 200+ students complete their Hifz.',
                'icon'              => 'Brain',
                'age_group'         => null,
                'level'             => 'Intermediate',
                'duration_months'   => null,
                'features'          => ['Daily memorization targets', 'Systematic revision schedule', 'Dedicated Hifz teacher', 'Flexible pace options'],
                'seo_title'         => 'Hifz Online | Quran Memorization Program | Azhary',
                'seo_description'   => 'Memorize the Quran with expert guidance. Structured Hifz program with dedicated teacher, daily targets, and systematic revision. Free trial class.',
                'outcomes'          => ['Memorize new Quran portions daily using proven techniques', 'Build a systematic revision schedule that ensures long-term retention', 'Recite memorized portions with correct Tajweed', 'Develop the discipline and consistency Hifz requires', 'Complete your Hifz journey with full teacher accountability'],
                'curriculum'        => [
                    ['module' => 'Hifz Foundation & Assessment', 'topics' => ['Evaluating Tajweed level before starting', 'Memorization technique selection — 5 proven methods', 'Personalized daily target setting']],
                    ['module' => 'New Memorization (Hifz Jadeed)', 'topics' => ['Daily new verse intake adjusted to student pace', 'Same-day repetition drills', 'Teacher verification of each new portion']],
                    ['module' => 'Recent Revision (Manzil Qareeb)', 'topics' => ['Daily review of last 7 days of memorization', 'Strengthening weak portions', 'Catching and correcting errors early']],
                    ['module' => 'Old Revision (Manzil Qadeem)', 'topics' => ['Weekly full-Juz revision', 'Systematic coverage of all completed portions', 'Long-term retention strategies']],
                    ['module' => 'Final Review & Khatm', 'topics' => ['Completing the full Quran in sequence', 'Extended recitation sessions with teacher', 'Final Khatm certification']],
                ],
                'personas'          => [
                    ['title' => 'Students Who Want to Become Hafiz', 'description' => 'You have decided to memorize the Quran and need a structured, accountable program with expert guidance.'],
                    ['title' => 'Children in Hifz Programs', 'description' => 'Young students aged 7+ who can read Quran well and are ready to begin memorization with full teacher support.'],
                    ['title' => 'Adults Resuming Hifz', 'description' => "You started memorizing years ago but stopped. We'll assess what you retained, strengthen it, and continue systematically."],
                ],
                'faqs'              => [
                    ['q' => 'What are the prerequisites for starting Hifz?', 'a' => 'You should be able to read the Quran fluently with at least basic Tajweed. We assess every student before starting and recommend Tajweed correction if needed.'],
                    ['q' => 'How many pages can I memorize per day?', 'a' => 'This varies by student. Beginners typically start at half a page per day, working up to 1–2 pages as the habit develops. Your teacher sets realistic targets.'],
                    ['q' => 'What if I miss classes or fall behind?', 'a' => 'Life happens. We adjust the schedule and targets. Consistency matters more than speed — we never rush students at the expense of retention.'],
                    ['q' => 'How long does full Hifz take online?', 'a' => 'Full Hifz (30 Juz) takes 2–5 years depending on pace, consistency, and student age. Focused adult students can complete it in 2–3 years.'],
                    ['q' => 'Do you offer revision-only classes for existing Huffaz?', 'a' => 'Yes — we have a Hifz revision track for students who have already memorized portions of the Quran and need structured review to maintain and strengthen it.'],
                    ['q' => 'Is a female Hifz teacher available?', 'a' => 'Yes — Sister Aisha Karimi and Sister Nour Al-Deen both specialize in Hifz and are available as female Hifz teachers.'],
                ],
                'related_slugs'    => ['tajweed-course', 'ijazah-program', 'quran-classes-for-kids'],
                'specialty_tags'   => ['Hifz / Memorization', 'Hifz', 'Revision Techniques', 'Tajweed'],
                'sort_order'       => 5,
            ],
            [
                'slug'              => 'ijazah-program',
                'title'             => 'Ijazah Program',
                'short_description' => 'Earn an authenticated Ijazah with an unbroken chain back to the Prophet ﷺ.',
                'long_description'  => 'The Ijazah is the highest credential in Quranic recitation — an authenticated license with an unbroken chain of transmission going back through the centuries to the Prophet ﷺ himself. Our teachers hold this chain and can pass it to qualified students.',
                'icon'              => 'Award',
                'age_group'         => null,
                'level'             => 'Advanced',
                'duration_months'   => null,
                'features'          => ['Authentic chain of transmission', 'One-on-one with Ijazah-holding sheikh', 'Hafs an Asim + option for other Riwayat', 'Certificate of Ijazah granted'],
                'seo_title'         => 'Online Ijazah Program | Authentic Chain | Azhary',
                'seo_description'   => 'Earn an authentic Ijazah with unbroken chain to the Prophet ﷺ. Hafs an Asim and other riwayat. Advanced program for qualified students.',
                'outcomes'          => ['Recite the complete Quran with flawless Tajweed', 'Understand all advanced Tajweed and Waqf rules', 'Receive an authenticated Ijazah certificate with full chain documentation', 'Gain the right to grant Ijazah to your own future students', 'Connect to an unbroken chain back to the Prophet ﷺ'],
                'curriculum'        => [
                    ['module' => 'Eligibility Assessment', 'topics' => ['Full Quran recitation test', 'Tajweed proficiency evaluation', 'Makharij verification by Sheikh Omar']],
                    ['module' => 'Tajweed Mastery Review', 'topics' => ['Advanced Makharij correction', 'All Madd categories — precision drilling', 'Waqf and Ibtidaa — complete coverage']],
                    ['module' => 'Full Quran Recitation (Tilawa)', 'topics' => ['Reciting the complete Quran to the Sheikh', 'Corrections and re-recitation where needed', 'Minimum standard: zero Tajweed errors per page']],
                    ['module' => 'Chain of Transmission (Isnad)', 'topics' => ['Understanding your personal chain back to the Prophet ﷺ', 'Documentation of the Isnad', 'Memorizing and reciting the chain']],
                    ['module' => 'Ijazah Granting', 'topics' => ['Final full or selected recitation', 'Written Ijazah certificate signed by Sheikh', 'Guidance on granting Ijazah to future students']],
                ],
                'personas'          => [
                    ['title' => 'Accomplished Huffaz', 'description' => "You've completed memorization and recite with strong Tajweed. The Ijazah is the natural next milestone."],
                    ['title' => 'Teachers Seeking Credentials', 'description' => 'You teach Quran and want authenticated credentials that establish your unbroken chain of transmission.'],
                    ['title' => 'Advanced Students of Tajweed', 'description' => 'You have mastered Tajweed and want the highest certification available in Quranic recitation.'],
                ],
                'faqs'              => [
                    ['q' => 'What are the prerequisites for the Ijazah program?', 'a' => 'You must have memorized the complete Quran (30 Juz) and be able to recite with strong Tajweed. An assessment is conducted before enrollment.'],
                    ['q' => 'Which Ijazah is offered?', 'a' => 'We primarily offer Ijazah in Hafs an Asim, the most widely read riwayah worldwide. Qualified students may also pursue other riwayat through our Ten Qiraat program.'],
                    ['q' => 'Is the Ijazah authentic?', 'a' => 'Yes — our teachers hold authenticated chains that go back to the Prophet ﷺ through an unbroken sequence of scholars. The full chain is documented in every Ijazah certificate.'],
                    ['q' => 'How long does the Ijazah program take?', 'a' => 'This depends on your starting level. Most students who are already Huffaz with strong Tajweed complete the program in 6–18 months of regular sessions.'],
                    ['q' => 'Can I grant Ijazah to others after receiving mine?', 'a' => 'Yes — the Ijazah grants you the right to teach and grant Ijazah to your own students, continuing the chain.'],
                    ['q' => 'Is it possible to get Ijazah without full Hifz?', 'a' => 'No — full Hifz (memorization of all 30 Juz) is a non-negotiable prerequisite for the Ijazah in most valid scholarly chains.'],
                ],
                'related_slugs'    => ['hifz-memorization', 'tajweed-course', 'ten-qiraat'],
                'specialty_tags'   => ['Ijazah', 'Ten Qiraat', 'Tajweed', 'Tafseer'],
                'sort_order'       => 6,
            ],
            [
                'slug'              => 'arabic-for-non-arabs',
                'title'             => 'Arabic for Non-Arabs',
                'short_description' => 'Learn Modern Standard Arabic and conversational Arabic from scratch.',
                'long_description'  => 'Designed for students with zero Arabic background. Start with the alphabet, progress to reading, writing, and conversation in Modern Standard Arabic. We also offer a Quranic Arabic track to understand the Quran directly in its original language.',
                'icon'              => 'Globe',
                'age_group'         => null,
                'level'             => 'Beginner',
                'duration_months'   => '6–18',
                'features'          => ['From zero to conversational', 'MSA + Quranic Arabic tracks', 'Native Arab teachers', 'Grammar + vocabulary focus'],
                'seo_title'         => 'Arabic for Non-Arabs Online | Learn Arabic | Azhary',
                'seo_description'   => 'Learn Arabic from scratch with native Arab teachers. MSA and Quranic Arabic tracks. Beginner to conversational in 6–18 months. Free trial class.',
                'outcomes'          => ['Read and write Arabic script fluently', 'Hold basic conversations in Modern Standard Arabic', 'Understand the structure of Arabic grammar (Nahw)', 'Read and comprehend Quranic Arabic vocabulary', 'Build a vocabulary of 1,000+ core Arabic words'],
                'curriculum'        => [
                    ['module' => 'Arabic Alphabet & Writing', 'topics' => ['All 29 letters and their forms', 'Writing from right to left', 'Short vowels and their omission in texts']],
                    ['module' => 'Basic Grammar (Nahw Foundations)', 'topics' => ['Nouns, verbs, and particles', 'Masculine/feminine, singular/plural', 'Sentence structure: subject + predicate']],
                    ['module' => 'Vocabulary & Conversations', 'topics' => ['Daily life vocabulary — 500 core words', 'Greetings, numbers, time, family, and places', 'Short conversation practice with teacher']],
                    ['module' => 'Intermediate Grammar', 'topics' => ['Verb conjugation across all tenses', 'Idaafa (possessive construction)', 'Adjective agreement']],
                    ['module' => 'Quranic Arabic Track (Optional)', 'topics' => ['Quranic vocabulary and grammar patterns', 'Reading and translating short Quranic passages', 'Understanding the Quran directly in Arabic']],
                ],
                'personas'          => [
                    ['title' => 'Non-Arab Muslims', 'description' => 'You want to understand the Quran and Islamic texts in their original language. This course builds that foundation.'],
                    ['title' => 'Language Learners', 'description' => 'You love languages and want to add Arabic — one of the most widely spoken languages in the world — to your repertoire.'],
                    ['title' => 'Students Preparing for Quran Studies', 'description' => 'Understanding Arabic deeply enhances your Tafseer study, Tajweed comprehension, and overall connection to the Quran.'],
                ],
                'faqs'              => [
                    ['q' => 'Which Arabic dialect do you teach?', 'a' => 'We teach Modern Standard Arabic (MSA / Fussha), which is used across all Arab countries, in media, and in Islamic texts. We also offer a Quranic Arabic track focused specifically on the language of the Quran.'],
                    ['q' => 'How long does it take to become conversational in Arabic?', 'a' => 'With 3 sessions per week, most students reach basic conversational ability in 6–12 months and a strong foundation in 12–18 months.'],
                    ['q' => 'Is Arabic difficult to learn?', 'a' => "Arabic has a different script and grammatical structure from European languages, but it's very systematic once you learn the patterns. Our teachers are experienced in making it accessible."],
                    ['q' => 'Are your teachers native Arabic speakers?', 'a' => 'Yes — all our Arabic teachers are native Arabic speakers from Egypt, Morocco, or the Levant, trained in linguistics and Arabic pedagogy.'],
                    ['q' => 'Do you offer a Quranic Arabic track specifically?', 'a' => 'Yes — students can choose an MSA track, a Quranic Arabic track, or a combined curriculum. We recommend the combined track for Muslim students who want to understand their prayers and the Quran.'],
                ],
                'related_slugs'    => ['tafseer-course', 'quran-classes-for-adults', 'islamic-studies'],
                'specialty_tags'   => ['Arabic for Non-Arabs', 'Quranic Arabic', 'Islamic Studies'],
                'sort_order'       => 7,
            ],
            [
                'slug'              => 'tafseer-course',
                'title'             => 'Tafseer',
                'short_description' => 'Understand the meaning and wisdom behind the words of Allah.',
                'long_description'  => 'Go beyond recitation — understand what Allah says. Our Tafseer course explains the meaning, context, and wisdom of the Quran verse by verse, drawing on classical scholarship and making it relevant to modern life.',
                'icon'              => 'Lightbulb',
                'age_group'         => null,
                'level'             => 'Intermediate',
                'duration_months'   => null,
                'features'          => ['Verse-by-verse explanation', 'Context and Asbab al-Nuzul', 'Classical + modern scholarship', 'Available in English'],
                'seo_title'         => 'Tafseer Course Online | Understand the Quran | Azhary',
                'seo_description'   => 'Go beyond recitation — understand the meaning of the Quran verse by verse. Classical and contemporary Tafseer in English. Free trial class.',
                'outcomes'          => ['Understand the meaning of every verse you study', 'Learn the historical context (Asbab al-Nuzul) of key verses', 'Connect Quranic guidance to everyday modern life', 'Study major classical Tafseer works with teacher guidance', 'Develop a deeper spiritual connection to the Quran'],
                'curriculum'        => [
                    ['module' => 'Introduction to Tafseer', 'topics' => ['What is Tafseer? History and methodology', 'Major classical works: Ibn Kathir, Al-Tabari, Al-Qurtubi', 'Asbab al-Nuzul — occasions of revelation']],
                    ['module' => 'Juz Amma — Short Surahs', 'topics' => ['Surah Al-Fatiha in depth', 'Surahs from An-Nas to An-Naba', 'Themes, lessons, and practical applications']],
                    ['module' => 'Thematic Quranic Study', 'topics' => ['Tawheed and the names of Allah', 'Stories of the Prophets', 'Ethics, morality, and social justice in the Quran']],
                    ['module' => 'Selected Longer Surahs', 'topics' => ['Surah Al-Baqarah — major passages', 'Surah Yaseen, Al-Kahf, and Al-Mulk', 'Context and major scholarly opinions']],
                    ['module' => 'Applying the Quran Today', 'topics' => ['Connecting verses to contemporary life', 'Personal reflection methodology', 'Discussion and Q&A with teacher']],
                ],
                'personas'          => [
                    ['title' => 'Quran Readers Seeking Depth', 'description' => 'You read the Quran regularly but want to truly understand what Allah is saying — not just recite the words.'],
                    ['title' => 'Islamic Knowledge Seekers', 'description' => 'You study Islam seriously and want a structured, scholarly approach to understanding the Quran.'],
                    ['title' => 'Arabic Language Students', 'description' => 'Your Arabic is developing and studying Tafseer enhances both your language comprehension and Quranic connection.'],
                ],
                'faqs'              => [
                    ['q' => 'Do I need to know Arabic to study Tafseer?', 'a' => 'No — our Tafseer course is taught in English, drawing on classical Arabic sources. Some basic Quranic vocabulary helps, but it is not required.'],
                    ['q' => 'Which Tafseer books do you use?', 'a' => 'We draw primarily on Tafseer Ibn Kathir and Al-Baghawi for classical scholarship, supplemented with contemporary works where relevant.'],
                    ['q' => 'Can I request a specific surah to focus on?', 'a' => 'Yes — we offer both structured curriculum-based Tafseer and student-led study of specific surahs. Let your teacher know your interests.'],
                    ['q' => 'How is this different from Islamic Studies?', 'a' => 'Tafseer focuses exclusively on the meaning and exegesis of the Quran. Islamic Studies is broader — covering Aqeedah, Fiqh, Seerah, and history in addition to the Quran.'],
                    ['q' => 'Is Tafseer suitable for beginners in Islamic knowledge?', 'a' => 'Yes — we adjust the depth and complexity based on your existing knowledge. Beginners start with accessible commentary; advanced students go deeper into scholarly differences of opinion.'],
                ],
                'related_slugs'    => ['islamic-studies', 'arabic-for-non-arabs', 'quran-classes-for-adults'],
                'specialty_tags'   => ['Tafseer', 'Islamic Studies', 'Seerah', 'Aqeedah'],
                'sort_order'       => 8,
            ],
            [
                'slug'              => 'islamic-studies',
                'title'             => 'Islamic Studies',
                'short_description' => 'Aqeedah, Seerah, Fiqh, and Islamic history for all ages.',
                'long_description'  => 'A comprehensive Islamic education covering the pillars of faith, the life of the Prophet ﷺ, Islamic jurisprudence, and the history of Islam — structured for both children and adults.',
                'icon'              => 'BookMarked',
                'age_group'         => null,
                'level'             => 'All Levels',
                'duration_months'   => null,
                'features'          => ['Aqeedah (belief)', 'Seerah (Prophetic biography)', 'Fiqh (Islamic rulings)', 'Islamic history'],
                'seo_title'         => 'Islamic Studies Online | Aqeedah, Seerah, Fiqh | Azhary',
                'seo_description'   => 'Comprehensive Islamic education covering Aqeedah, Seerah, Fiqh, and Islamic history. For children and adults. 1-on-1 with certified scholars. Free trial.',
                'outcomes'          => ['Understand the six pillars of faith (Aqeedah) clearly', 'Know the life of the Prophet ﷺ in meaningful detail', 'Apply basic Fiqh rulings in daily worship', 'Understand Islamic history from the Prophet ﷺ to the present', 'Articulate Islamic values clearly and confidently'],
                'curriculum'        => [
                    ['module' => 'Aqeedah (Islamic Belief)', 'topics' => ['Six pillars of faith', 'Tawheed — the oneness of Allah', 'Angels, books, prophets, and the Day of Judgment']],
                    ['module' => 'Seerah (Prophetic Biography)', 'topics' => ['The life of Muhammad ﷺ — birth to prophethood', 'Key events in Makkah and Madinah', 'Character and legacy of the Prophet ﷺ']],
                    ['module' => 'Fiqh (Islamic Jurisprudence)', 'topics' => ['Tahara (purification) and Salah (prayer)', 'Zakat, Sawm (fasting), and Hajj overview', 'Halal/haram guidelines and ethics']],
                    ['module' => 'Islamic History', 'topics' => ['The Rightly Guided Caliphs', 'The Golden Age of Islam', 'The Islamic world today']],
                    ['module' => 'Islamic Character & Values', 'topics' => ['Akhlaq — manners and character in Islam', 'Community and family in Islamic tradition', 'Engaging with the modern world as a Muslim']],
                ],
                'personas'          => [
                    ['title' => 'Muslim Adults Seeking Knowledge', 'description' => 'You are practicing Islam but want structured, authentic knowledge of its foundations — taught by qualified scholars.'],
                    ['title' => 'Parents Educating Their Children', 'description' => 'You want your children to grow up with Islamic knowledge and values, taught in an engaging, age-appropriate way.'],
                    ['title' => 'Reverts to Islam', 'description' => 'You are new to Islam and need a comprehensive foundation — what to believe, how to worship, and how to live as a Muslim.'],
                ],
                'faqs'              => [
                    ['q' => 'Which madhab (school of jurisprudence) do you follow?', 'a' => 'Our teachers present the mainstream position on most issues and note major differences of opinion. We do not impose a single madhab and welcome students from all backgrounds.'],
                    ['q' => 'Is this course available for children?', 'a' => 'Yes — we have child-appropriate Islamic Studies tracks for ages 5 and above, taught by teachers experienced with young learners.'],
                    ['q' => 'How is this different from the Tafseer course?', 'a' => 'Islamic Studies is comprehensive — covering belief, worship, Prophetic biography, and history. The Tafseer course focuses exclusively on Quran interpretation.'],
                    ['q' => 'Can I focus on just one topic, like Seerah?', 'a' => "Yes — we offer Seerah-only, Fiqh-only, and Aqeedah-only tracks. You don't have to take the full curriculum if you want to focus."],
                    ['q' => 'Are your teachers qualified to teach Islamic jurisprudence?', 'a' => 'Yes — all Islamic Studies teachers hold degrees from Al-Azhar or equivalent institutions and are qualified to teach all subjects in the curriculum.'],
                ],
                'related_slugs'    => ['tafseer-course', 'quran-classes-for-kids', 'arabic-for-non-arabs'],
                'specialty_tags'   => ['Islamic Studies', 'Seerah', 'Aqeedah', 'Islamic Studies for Kids'],
                'sort_order'       => 9,
            ],
            [
                'slug'              => 'ten-qiraat',
                'title'             => 'Ten Qiraat',
                'short_description' => 'Advanced program covering all ten authentic modes of Quranic recitation.',
                'long_description'  => 'An advanced course for accomplished Hafiz students who wish to master all ten authenticated modes of Quranic recitation. Taught by Sheikh Omar Al-Hassan, who holds Ijazah in all ten Qiraat.',
                'icon'              => 'Layers',
                'age_group'         => null,
                'level'             => 'Advanced',
                'duration_months'   => null,
                'features'          => ['All ten Qiraat covered', 'Taught by Qiraat specialist', 'Prerequisite: Hafs Ijazah', 'Isnad (chain) provided'],
                'seo_title'         => 'Ten Qiraat Online Program | Advanced Recitation | Azhary',
                'seo_description'   => 'Master all ten authentic modes of Quranic recitation (Qiraat). Advanced program for qualified Huffaz. Taught by a Sheikh with Ijazah in all ten. Free trial.',
                'outcomes'          => ['Recite the Quran in all ten authenticated Qiraat', 'Understand the differences between each riwayah and its specific rules', 'Receive Isnad (chain) documentation for each Qiraah completed', 'Qualify to grant Ijazah in the Qiraat you complete', 'Deepen understanding of Quranic Arabic through variant readings'],
                'curriculum'        => [
                    ['module' => 'Introduction to the Ten Qiraat', 'topics' => ['History and authority of the ten Qiraat', "Al-Shatibiyya and Al-Durra — the classical poems", 'Rules common to all Qiraat vs. variant-specific rules']],
                    ['module' => "Qiraat 1–4: Al-Shatibiyya", 'topics' => ["Nafi' — Warsh and Qaloon", "Ibn Kathir — Al-Bazzi and Qunbul", "Abu Amr — Al-Duri and Al-Susi", "Ibn Amir — Hisham and Ibn Dhakwan"]],
                    ['module' => "Qiraat 5–7: Al-Shatibiyya (cont.)", 'topics' => ["Asim — Hafs and Shu'ba", "Hamzah — Khalaf and Khallad", "Al-Kisa'i — Al-Layth and Al-Duri"]],
                    ['module' => 'Qiraat 8–10: Al-Durra', 'topics' => ['Abu Jaafar — Ibn Wardaan and Ibn Jummaz', 'Yaqoob — Ruways and Rawh', 'Khalaf al-Aashir — Ishaq and Idris']],
                    ['module' => 'Full Recitation & Isnad', 'topics' => ['Reciting the complete Quran in each Qiraah', 'Documentation and certification per Qiraah', 'Preparation to grant Ijazah to future students']],
                ],
                'personas'          => [
                    ['title' => 'Hafiz with Ijazah in Hafs', 'description' => 'You have completed your Hifz and received Ijazah in Hafs an Asim and want to advance to all ten Qiraat.'],
                    ['title' => 'Advanced Scholars of Quran', 'description' => 'You are deeply engaged in Quranic sciences and want the highest level of recitation scholarship.'],
                    ['title' => 'Teachers Seeking Advanced Credentials', 'description' => 'You teach Quran and want to offer your students multiple Qiraat — which requires your own certification first.'],
                ],
                'faqs'              => [
                    ['q' => 'What are the prerequisites for the Ten Qiraat program?', 'a' => 'You must have completed Hifz (full memorization) and hold Ijazah in Hafs an Asim, or equivalent certification. We assess each student before enrollment.'],
                    ['q' => 'How long does mastering all ten Qiraat take?', 'a' => 'This is a long-term program — typically 5–10 years of regular study. Most students complete 2–3 Qiraat per year depending on pace and commitment.'],
                    ['q' => 'Do I have to complete all ten, or can I stop after some?', 'a' => 'You can complete any number of Qiraat and receive Isnad for each one. There is no requirement to complete all ten if your goal is a specific riwayah.'],
                    ['q' => 'Who teaches this program?', 'a' => 'This program is taught exclusively by Sheikh Omar Al-Hassan, who holds Ijazah in all ten Qiraat with an authenticated Mutawatir chain.'],
                    ['q' => 'Is there a certificate for each Qiraah completed?', 'a' => 'Yes — upon completing each Qiraah and passing the recitation test, you receive a separate Isnad certificate with the full chain documented.'],
                ],
                'related_slugs'    => ['ijazah-program', 'hifz-memorization', 'tajweed-course'],
                'specialty_tags'   => ['Ten Qiraat', 'Ijazah', 'Tajweed'],
                'sort_order'       => 10,
            ],
            [
                'slug'              => 'female-quran-teachers',
                'title'             => 'Female Teachers',
                'short_description' => 'Learn with certified female teachers — comfortable, safe, and effective.',
                'long_description'  => 'For sisters who prefer to learn from female teachers, all our courses are available with our certified female teaching team. All teachers hold Ijazah or equivalent credentials and are experienced professionals.',
                'icon'              => 'Heart',
                'age_group'         => null,
                'level'             => 'All Levels',
                'duration_months'   => null,
                'features'          => ['Female teachers only', 'All courses available', 'Same certifications and quality', 'Flexible scheduling'],
                'seo_title'         => 'Female Quran Teachers Online | Learn with Sisters | Azhary',
                'seo_description'   => 'All courses available with certified female Quran teachers. Safe, comfortable, effective. Tajweed, Hifz, Arabic, and more. Free trial with a female teacher.',
                'outcomes'          => ['Complete any Azhary course with a certified female teacher', 'Learn in a comfortable, focused, and distraction-free environment', 'Receive the same quality and credentials as all Azhary teachers', 'Work with teachers who understand your specific needs and schedule', 'Achieve your Quran goals — recitation, Hifz, Tajweed, or Ijazah'],
                'curriculum'        => [
                    ['module' => 'All Standard Courses Available', 'topics' => ['Noorani Qaida with female teacher', 'Tajweed course with female teacher', 'Hifz program with female teacher']],
                    ['module' => 'Specialized Programs', 'topics' => ['Quran for Kids — female specialist teachers', 'Arabic for Non-Arabs with female teacher', 'Islamic Studies with female scholar']],
                    ['module' => 'Advanced Programs', 'topics' => ['Ijazah program — female teacher Ijazah chain available', 'Tafseer with female Islamic scholar', 'Quran for Adults with female teacher']],
                    ['module' => 'Scheduling & Flexibility', 'topics' => ['All timezones and days of the week', 'Morning, afternoon, and evening slots', 'Weekend sessions available']],
                    ['module' => 'Teacher Selection', 'topics' => ['Meet your teacher before committing', 'Switch teachers if needed at any time', 'Request specific credentials or specialties']],
                ],
                'personas'          => [
                    ['title' => 'Sisters Who Prefer Female Teachers', 'description' => 'For modesty or personal comfort, you prefer to learn exclusively with female teachers — and every one of our sisters holds full certifications.'],
                    ['title' => 'Parents Seeking Female Teachers for Daughters', 'description' => 'You want your daughter to have a positive, comfortable learning experience with a qualified female teacher.'],
                    ['title' => 'Schools & Institutions', 'description' => 'Your Islamic school or community center needs qualified female Quran teachers for classes, events, or ongoing programs.'],
                ],
                'faqs'              => [
                    ['q' => 'Are the female teachers at Azhary certified?', 'a' => 'Yes — all female teachers hold Ijazah or equivalent credentials from recognized Islamic institutions. They undergo the same rigorous vetting as our male teachers.'],
                    ['q' => 'Can female teachers grant Ijazah?', 'a' => 'Yes — Sister Aisha Karimi holds an authenticated Ijazah in Hafs an Asim and is qualified to grant Ijazah to her students.'],
                    ['q' => 'Are all courses available with female teachers?', 'a' => 'Yes — every course we offer is available with a female teacher, including Noorani Qaida, Tajweed, Hifz, Arabic, Islamic Studies, and Tafseer.'],
                    ['q' => 'Is the quality the same as male teachers?', 'a' => 'Absolutely. We apply identical vetting standards to all teachers regardless of gender. Every teacher must pass our full certification process.'],
                    ['q' => "Can I request a specific female teacher by name?", 'a' => "You can request a specific teacher, and we will match you if that teacher has availability. If not, we'll find you a teacher with the same specialties and credentials."],
                    ['q' => 'Are sessions with female teachers more expensive?', 'a' => 'No — pricing is the same regardless of which teacher you are matched with. There is no premium for female teachers.'],
                ],
                'related_slugs'    => ['quran-classes-for-adults', 'hifz-memorization', 'tajweed-course'],
                'specialty_tags'   => ['Quran for Kids', 'Tajweed', 'Hifz', 'Quran for Adults', 'Noorani Qaida', 'Arabic for Non-Arabs', 'Islamic Studies'],
                'sort_order'       => 11,
            ],
        ];

        foreach ($courses as $data) {
            Course::updateOrCreate(['slug' => $data['slug']], $data);
        }
    }
}
