/**
 * digits: [min, max] — expected local digit count after the country code,
 * in E.164 format (no leading trunk zero). Used for WhatsApp number validation.
 */
export const COUNTRIES = [
  { code: 'AE', name: 'United Arab Emirates', timezone: 'Asia/Dubai',                       dialCode: '+971',  digits: [9,  9]  },
  { code: 'AF', name: 'Afghanistan',           timezone: 'Asia/Kabul',                       dialCode: '+93',   digits: [9,  9]  },
  { code: 'AL', name: 'Albania',               timezone: 'Europe/Tirane',                    dialCode: '+355',  digits: [9,  9]  },
  { code: 'DZ', name: 'Algeria',               timezone: 'Africa/Algiers',                   dialCode: '+213',  digits: [9,  9]  },
  { code: 'AO', name: 'Angola',                timezone: 'Africa/Luanda',                    dialCode: '+244',  digits: [9,  9]  },
  { code: 'AR', name: 'Argentina',             timezone: 'America/Argentina/Buenos_Aires',   dialCode: '+54',   digits: [10, 11] },
  { code: 'AU', name: 'Australia',             timezone: 'Australia/Sydney',                 dialCode: '+61',   digits: [9,  9]  },
  { code: 'AT', name: 'Austria',               timezone: 'Europe/Vienna',                    dialCode: '+43',   digits: [10, 11] },
  { code: 'AZ', name: 'Azerbaijan',            timezone: 'Asia/Baku',                        dialCode: '+994',  digits: [9,  9]  },
  { code: 'BH', name: 'Bahrain',               timezone: 'Asia/Bahrain',                     dialCode: '+973',  digits: [8,  8]  },
  { code: 'BD', name: 'Bangladesh',            timezone: 'Asia/Dhaka',                       dialCode: '+880',  digits: [10, 10] },
  { code: 'BY', name: 'Belarus',               timezone: 'Europe/Minsk',                     dialCode: '+375',  digits: [9,  9]  },
  { code: 'BE', name: 'Belgium',               timezone: 'Europe/Brussels',                  dialCode: '+32',   digits: [9,  9]  },
  { code: 'BJ', name: 'Benin',                 timezone: 'Africa/Porto-Novo',                dialCode: '+229',  digits: [8,  8]  },
  { code: 'BT', name: 'Bhutan',                timezone: 'Asia/Thimphu',                     dialCode: '+975',  digits: [8,  8]  },
  { code: 'BO', name: 'Bolivia',               timezone: 'America/La_Paz',                   dialCode: '+591',  digits: [8,  8]  },
  { code: 'BA', name: 'Bosnia and Herzegovina',timezone: 'Europe/Sarajevo',                  dialCode: '+387',  digits: [8,  8]  },
  { code: 'BW', name: 'Botswana',              timezone: 'Africa/Gaborone',                  dialCode: '+267',  digits: [7,  8]  },
  { code: 'BR', name: 'Brazil',                timezone: 'America/Sao_Paulo',                dialCode: '+55',   digits: [10, 11] },
  { code: 'BN', name: 'Brunei',                timezone: 'Asia/Brunei',                      dialCode: '+673',  digits: [7,  7]  },
  { code: 'BG', name: 'Bulgaria',              timezone: 'Europe/Sofia',                     dialCode: '+359',  digits: [9,  9]  },
  { code: 'BF', name: 'Burkina Faso',          timezone: 'Africa/Ouagadougou',               dialCode: '+226',  digits: [8,  8]  },
  { code: 'KH', name: 'Cambodia',              timezone: 'Asia/Phnom_Penh',                  dialCode: '+855',  digits: [8,  9]  },
  { code: 'CM', name: 'Cameroon',              timezone: 'Africa/Douala',                    dialCode: '+237',  digits: [9,  9]  },
  { code: 'CA', name: 'Canada',                timezone: 'America/Toronto',                  dialCode: '+1',    digits: [10, 10] },
  { code: 'CF', name: 'Central African Republic', timezone: 'Africa/Bangui',                 dialCode: '+236',  digits: [8,  8]  },
  { code: 'TD', name: 'Chad',                  timezone: 'Africa/Ndjamena',                  dialCode: '+235',  digits: [8,  8]  },
  { code: 'CL', name: 'Chile',                 timezone: 'America/Santiago',                 dialCode: '+56',   digits: [9,  9]  },
  { code: 'CN', name: 'China',                 timezone: 'Asia/Shanghai',                    dialCode: '+86',   digits: [11, 11] },
  { code: 'CO', name: 'Colombia',              timezone: 'America/Bogota',                   dialCode: '+57',   digits: [10, 10] },
  { code: 'KM', name: 'Comoros',               timezone: 'Indian/Comoro',                    dialCode: '+269',  digits: [7,  7]  },
  { code: 'CG', name: 'Congo',                 timezone: 'Africa/Brazzaville',               dialCode: '+242',  digits: [9,  9]  },
  { code: 'CD', name: 'Congo (DRC)',            timezone: 'Africa/Kinshasa',                  dialCode: '+243',  digits: [9,  9]  },
  { code: 'HR', name: 'Croatia',               timezone: 'Europe/Zagreb',                    dialCode: '+385',  digits: [8,  9]  },
  { code: 'CY', name: 'Cyprus',                timezone: 'Asia/Nicosia',                     dialCode: '+357',  digits: [8,  8]  },
  { code: 'CZ', name: 'Czech Republic',        timezone: 'Europe/Prague',                    dialCode: '+420',  digits: [9,  9]  },
  { code: 'DK', name: 'Denmark',               timezone: 'Europe/Copenhagen',                dialCode: '+45',   digits: [8,  8]  },
  { code: 'DJ', name: 'Djibouti',              timezone: 'Africa/Djibouti',                  dialCode: '+253',  digits: [8,  8]  },
  { code: 'EG', name: 'Egypt',                 timezone: 'Africa/Cairo',                     dialCode: '+20',   digits: [10, 10] },
  { code: 'ET', name: 'Ethiopia',              timezone: 'Africa/Addis_Ababa',               dialCode: '+251',  digits: [9,  9]  },
  { code: 'FI', name: 'Finland',               timezone: 'Europe/Helsinki',                  dialCode: '+358',  digits: [9,  10] },
  { code: 'FR', name: 'France',                timezone: 'Europe/Paris',                     dialCode: '+33',   digits: [9,  9]  },
  { code: 'GA', name: 'Gabon',                 timezone: 'Africa/Libreville',                dialCode: '+241',  digits: [7,  8]  },
  { code: 'GM', name: 'Gambia',                timezone: 'Africa/Banjul',                    dialCode: '+220',  digits: [7,  7]  },
  { code: 'GE', name: 'Georgia',               timezone: 'Asia/Tbilisi',                     dialCode: '+995',  digits: [9,  9]  },
  { code: 'DE', name: 'Germany',               timezone: 'Europe/Berlin',                    dialCode: '+49',   digits: [10, 11] },
  { code: 'GH', name: 'Ghana',                 timezone: 'Africa/Accra',                     dialCode: '+233',  digits: [9,  9]  },
  { code: 'GR', name: 'Greece',                timezone: 'Europe/Athens',                    dialCode: '+30',   digits: [10, 10] },
  { code: 'GN', name: 'Guinea',                timezone: 'Africa/Conakry',                   dialCode: '+224',  digits: [9,  9]  },
  { code: 'GW', name: 'Guinea-Bissau',         timezone: 'Africa/Bissau',                    dialCode: '+245',  digits: [7,  7]  },
  { code: 'HN', name: 'Honduras',              timezone: 'America/Tegucigalpa',              dialCode: '+504',  digits: [8,  8]  },
  { code: 'HK', name: 'Hong Kong',             timezone: 'Asia/Hong_Kong',                   dialCode: '+852',  digits: [8,  8]  },
  { code: 'HU', name: 'Hungary',               timezone: 'Europe/Budapest',                  dialCode: '+36',   digits: [9,  9]  },
  { code: 'IN', name: 'India',                 timezone: 'Asia/Kolkata',                     dialCode: '+91',   digits: [10, 10] },
  { code: 'ID', name: 'Indonesia',             timezone: 'Asia/Jakarta',                     dialCode: '+62',   digits: [9,  12] },
  { code: 'IR', name: 'Iran',                  timezone: 'Asia/Tehran',                      dialCode: '+98',   digits: [10, 10] },
  { code: 'IQ', name: 'Iraq',                  timezone: 'Asia/Baghdad',                     dialCode: '+964',  digits: [10, 10] },
  { code: 'IE', name: 'Ireland',               timezone: 'Europe/Dublin',                    dialCode: '+353',  digits: [9,  9]  },
  { code: 'IL', name: 'Israel',                timezone: 'Asia/Jerusalem',                   dialCode: '+972',  digits: [9,  9]  },
  { code: 'IT', name: 'Italy',                 timezone: 'Europe/Rome',                      dialCode: '+39',   digits: [9,  10] },
  { code: 'CI', name: 'Ivory Coast',           timezone: 'Africa/Abidjan',                   dialCode: '+225',  digits: [10, 10] },
  { code: 'JM', name: 'Jamaica',               timezone: 'America/Jamaica',                  dialCode: '+1876', digits: [7,  7]  },
  { code: 'JP', name: 'Japan',                 timezone: 'Asia/Tokyo',                       dialCode: '+81',   digits: [10, 10] },
  { code: 'JO', name: 'Jordan',                timezone: 'Asia/Amman',                       dialCode: '+962',  digits: [9,  9]  },
  { code: 'KZ', name: 'Kazakhstan',            timezone: 'Asia/Almaty',                      dialCode: '+7',    digits: [10, 10] },
  { code: 'KE', name: 'Kenya',                 timezone: 'Africa/Nairobi',                   dialCode: '+254',  digits: [9,  9]  },
  { code: 'KW', name: 'Kuwait',                timezone: 'Asia/Kuwait',                      dialCode: '+965',  digits: [8,  8]  },
  { code: 'KG', name: 'Kyrgyzstan',            timezone: 'Asia/Bishkek',                     dialCode: '+996',  digits: [9,  9]  },
  { code: 'LA', name: 'Laos',                  timezone: 'Asia/Vientiane',                   dialCode: '+856',  digits: [8,  9]  },
  { code: 'LB', name: 'Lebanon',               timezone: 'Asia/Beirut',                      dialCode: '+961',  digits: [7,  8]  },
  { code: 'LY', name: 'Libya',                 timezone: 'Africa/Tripoli',                   dialCode: '+218',  digits: [9,  9]  },
  { code: 'MY', name: 'Malaysia',              timezone: 'Asia/Kuala_Lumpur',                dialCode: '+60',   digits: [9,  10] },
  { code: 'MV', name: 'Maldives',              timezone: 'Indian/Maldives',                  dialCode: '+960',  digits: [7,  7]  },
  { code: 'ML', name: 'Mali',                  timezone: 'Africa/Bamako',                    dialCode: '+223',  digits: [8,  8]  },
  { code: 'MR', name: 'Mauritania',            timezone: 'Africa/Nouakchott',                dialCode: '+222',  digits: [8,  8]  },
  { code: 'MX', name: 'Mexico',                timezone: 'America/Mexico_City',              dialCode: '+52',   digits: [10, 10] },
  { code: 'MD', name: 'Moldova',               timezone: 'Europe/Chisinau',                  dialCode: '+373',  digits: [8,  8]  },
  { code: 'MA', name: 'Morocco',               timezone: 'Africa/Casablanca',                dialCode: '+212',  digits: [9,  9]  },
  { code: 'MZ', name: 'Mozambique',            timezone: 'Africa/Maputo',                    dialCode: '+258',  digits: [9,  9]  },
  { code: 'MM', name: 'Myanmar',               timezone: 'Asia/Rangoon',                     dialCode: '+95',   digits: [8,  10] },
  { code: 'NA', name: 'Namibia',               timezone: 'Africa/Windhoek',                  dialCode: '+264',  digits: [9,  9]  },
  { code: 'NP', name: 'Nepal',                 timezone: 'Asia/Kathmandu',                   dialCode: '+977',  digits: [10, 10] },
  { code: 'NL', name: 'Netherlands',           timezone: 'Europe/Amsterdam',                 dialCode: '+31',   digits: [9,  9]  },
  { code: 'NZ', name: 'New Zealand',           timezone: 'Pacific/Auckland',                 dialCode: '+64',   digits: [8,  9]  },
  { code: 'NE', name: 'Niger',                 timezone: 'Africa/Niamey',                    dialCode: '+227',  digits: [8,  8]  },
  { code: 'NG', name: 'Nigeria',               timezone: 'Africa/Lagos',                     dialCode: '+234',  digits: [10, 10] },
  { code: 'MK', name: 'North Macedonia',       timezone: 'Europe/Skopje',                    dialCode: '+389',  digits: [8,  8]  },
  { code: 'NO', name: 'Norway',                timezone: 'Europe/Oslo',                      dialCode: '+47',   digits: [8,  8]  },
  { code: 'OM', name: 'Oman',                  timezone: 'Asia/Muscat',                      dialCode: '+968',  digits: [8,  8]  },
  { code: 'PK', name: 'Pakistan',              timezone: 'Asia/Karachi',                     dialCode: '+92',   digits: [10, 10] },
  { code: 'PS', name: 'Palestine',             timezone: 'Asia/Gaza',                        dialCode: '+970',  digits: [9,  9]  },
  { code: 'PA', name: 'Panama',                timezone: 'America/Panama',                   dialCode: '+507',  digits: [8,  8]  },
  { code: 'PY', name: 'Paraguay',              timezone: 'America/Asuncion',                 dialCode: '+595',  digits: [9,  9]  },
  { code: 'PE', name: 'Peru',                  timezone: 'America/Lima',                     dialCode: '+51',   digits: [9,  9]  },
  { code: 'PH', name: 'Philippines',           timezone: 'Asia/Manila',                      dialCode: '+63',   digits: [10, 10] },
  { code: 'PL', name: 'Poland',                timezone: 'Europe/Warsaw',                    dialCode: '+48',   digits: [9,  9]  },
  { code: 'PT', name: 'Portugal',              timezone: 'Europe/Lisbon',                    dialCode: '+351',  digits: [9,  9]  },
  { code: 'QA', name: 'Qatar',                 timezone: 'Asia/Qatar',                       dialCode: '+974',  digits: [8,  8]  },
  { code: 'RO', name: 'Romania',               timezone: 'Europe/Bucharest',                 dialCode: '+40',   digits: [9,  9]  },
  { code: 'RU', name: 'Russia',                timezone: 'Europe/Moscow',                    dialCode: '+7',    digits: [10, 10] },
  { code: 'RW', name: 'Rwanda',                timezone: 'Africa/Kigali',                    dialCode: '+250',  digits: [9,  9]  },
  { code: 'SA', name: 'Saudi Arabia',          timezone: 'Asia/Riyadh',                      dialCode: '+966',  digits: [9,  9]  },
  { code: 'SN', name: 'Senegal',               timezone: 'Africa/Dakar',                     dialCode: '+221',  digits: [9,  9]  },
  { code: 'RS', name: 'Serbia',                timezone: 'Europe/Belgrade',                  dialCode: '+381',  digits: [8,  9]  },
  { code: 'SL', name: 'Sierra Leone',          timezone: 'Africa/Freetown',                  dialCode: '+232',  digits: [8,  8]  },
  { code: 'SG', name: 'Singapore',             timezone: 'Asia/Singapore',                   dialCode: '+65',   digits: [8,  8]  },
  { code: 'SK', name: 'Slovakia',              timezone: 'Europe/Bratislava',                dialCode: '+421',  digits: [9,  9]  },
  { code: 'SI', name: 'Slovenia',              timezone: 'Europe/Ljubljana',                 dialCode: '+386',  digits: [8,  8]  },
  { code: 'SO', name: 'Somalia',               timezone: 'Africa/Mogadishu',                 dialCode: '+252',  digits: [7,  8]  },
  { code: 'ZA', name: 'South Africa',          timezone: 'Africa/Johannesburg',              dialCode: '+27',   digits: [9,  9]  },
  { code: 'SS', name: 'South Sudan',           timezone: 'Africa/Juba',                      dialCode: '+211',  digits: [9,  9]  },
  { code: 'ES', name: 'Spain',                 timezone: 'Europe/Madrid',                    dialCode: '+34',   digits: [9,  9]  },
  { code: 'LK', name: 'Sri Lanka',             timezone: 'Asia/Colombo',                     dialCode: '+94',   digits: [9,  9]  },
  { code: 'SD', name: 'Sudan',                 timezone: 'Africa/Khartoum',                  dialCode: '+249',  digits: [9,  9]  },
  { code: 'SE', name: 'Sweden',                timezone: 'Europe/Stockholm',                 dialCode: '+46',   digits: [9,  9]  },
  { code: 'CH', name: 'Switzerland',           timezone: 'Europe/Zurich',                    dialCode: '+41',   digits: [9,  9]  },
  { code: 'SY', name: 'Syria',                 timezone: 'Asia/Damascus',                    dialCode: '+963',  digits: [9,  9]  },
  { code: 'TW', name: 'Taiwan',                timezone: 'Asia/Taipei',                      dialCode: '+886',  digits: [9,  9]  },
  { code: 'TJ', name: 'Tajikistan',            timezone: 'Asia/Dushanbe',                    dialCode: '+992',  digits: [9,  9]  },
  { code: 'TZ', name: 'Tanzania',              timezone: 'Africa/Dar_es_Salaam',             dialCode: '+255',  digits: [9,  9]  },
  { code: 'TH', name: 'Thailand',              timezone: 'Asia/Bangkok',                     dialCode: '+66',   digits: [9,  9]  },
  { code: 'TG', name: 'Togo',                  timezone: 'Africa/Lome',                      dialCode: '+228',  digits: [8,  8]  },
  { code: 'TN', name: 'Tunisia',               timezone: 'Africa/Tunis',                     dialCode: '+216',  digits: [8,  8]  },
  { code: 'TR', name: 'Turkey',                timezone: 'Europe/Istanbul',                  dialCode: '+90',   digits: [10, 10] },
  { code: 'TM', name: 'Turkmenistan',          timezone: 'Asia/Ashgabat',                    dialCode: '+993',  digits: [8,  8]  },
  { code: 'UG', name: 'Uganda',                timezone: 'Africa/Kampala',                   dialCode: '+256',  digits: [9,  9]  },
  { code: 'UA', name: 'Ukraine',               timezone: 'Europe/Kyiv',                      dialCode: '+380',  digits: [9,  9]  },
  { code: 'GB', name: 'United Kingdom',        timezone: 'Europe/London',                    dialCode: '+44',   digits: [10, 10] },
  { code: 'US', name: 'United States',         timezone: 'America/New_York',                 dialCode: '+1',    digits: [10, 10] },
  { code: 'UY', name: 'Uruguay',               timezone: 'America/Montevideo',               dialCode: '+598',  digits: [8,  9]  },
  { code: 'UZ', name: 'Uzbekistan',            timezone: 'Asia/Tashkent',                    dialCode: '+998',  digits: [9,  9]  },
  { code: 'VE', name: 'Venezuela',             timezone: 'America/Caracas',                  dialCode: '+58',   digits: [10, 10] },
  { code: 'VN', name: 'Vietnam',               timezone: 'Asia/Ho_Chi_Minh',                 dialCode: '+84',   digits: [9,  10] },
  { code: 'YE', name: 'Yemen',                 timezone: 'Asia/Aden',                        dialCode: '+967',  digits: [9,  9]  },
  { code: 'ZM', name: 'Zambia',                timezone: 'Africa/Lusaka',                    dialCode: '+260',  digits: [9,  9]  },
  { code: 'ZW', name: 'Zimbabwe',              timezone: 'Africa/Harare',                    dialCode: '+263',  digits: [9,  9]  },
] as const

export type Country = typeof COUNTRIES[number]

export function flagEmoji(code: string) {
  return code
    .toUpperCase()
    .replace(/./g, (ch) => String.fromCodePoint(127397 + ch.charCodeAt(0)))
}
