import type { Lesson, LessonStatus } from '@/types/system/lesson'
import { CONSUMING_STATUSES } from '@/types/system/lesson'

/* Ordered list for the status dropdown / filter (consuming first, then non-consuming). */
export const LESSON_STATUSES: { value: LessonStatus; label: string }[] = [
  { value: 'attended',             label: 'Attended'            },
  { value: 'paid_absence',         label: 'Paid Absence'        },
  { value: 'cancelled_by_student', label: 'Cancelled (Student)' },
  { value: 'scheduled',            label: 'Scheduled'           },
  { value: 'absent',               label: 'Absent'              },
  { value: 'cancelled_by_teacher', label: 'Cancelled (Teacher)' },
  { value: 'trial',                label: 'Trial Lesson'        },
  { value: 'free',                 label: 'Free Lesson'         },
]

export const STATUS_LABEL: Record<LessonStatus, string> = {
  scheduled:            'Scheduled',
  attended:             'Attended',
  paid_absence:         'Paid Absence',
  absent:               'Absent',
  trial:                'Trial Lesson',
  free:                 'Free Lesson',
  cancelled_by_student: 'Cancelled (Student)',
  cancelled_by_teacher: 'Cancelled (Teacher)',
}

/* Pill colours for the list view status badge. */
export const STATUS_PILL: Record<LessonStatus, { bg: string; color: string }> = {
  scheduled:            { bg: '#EEF2FF', color: '#4338CA' },
  attended:             { bg: '#F0FDF4', color: '#15803D' },
  paid_absence:         { bg: '#FFF7ED', color: '#C2410C' },
  absent:               { bg: '#FEF2F2', color: '#B91C1C' },
  trial:                { bg: '#FEF9C3', color: '#A16207' },
  free:                 { bg: '#ECFEFF', color: '#0E7490' },
  cancelled_by_student: { bg: '#FEF2F2', color: '#B91C1C' },
  cancelled_by_teacher: { bg: '#F3F4F6', color: '#6B7280' },
}

export function isConsuming(status: LessonStatus): boolean {
  return CONSUMING_STATUSES.includes(status)
}

/** Session number shown in the calendar/list — 0.0 for non-consuming lessons. */
export function displaySessionHours(lesson: Lesson): string {
  return isConsuming(lesson.status) ? Number(lesson.session_number_hours).toFixed(1) : '0.0'
}

/* Calendar block colours (matches the old system):
 *  purple = recurring-schedule occurrence · neutral = one-off scheduled / trial
 *  green = paid package · red = pending (unpaid) consumed lesson · grey = teacher-cancelled */
const NEUTRAL = { bg: 'transparent', color: 'rgb(90 100 112)', border: '1px solid rgb(229 233 240)' }
const PURPLE  = { bg: '#F5F3FF', color: '#6D28D9', border: '1px solid #DDD6FE' }
const GREEN   = { bg: '#F0FDF4', color: '#15803D', border: '1px solid #BBF7D0' }
const RED     = { bg: '#FEF2F2', color: '#B91C1C', border: '1px solid #FECACA' }
const GREY    = { bg: '#F3F4F6', color: '#6B7280', border: '1px solid #E5E7EB' }

export function lessonBlockStyle(lesson: Lesson): { bg: string; color: string; border: string } {
  if (lesson.status === 'scheduled')            return lesson.schedule_id ? PURPLE : NEUTRAL
  if (lesson.status === 'trial' || lesson.status === 'free') return NEUTRAL
  if (lesson.status === 'cancelled_by_teacher') return GREY
  return lesson.package?.status === 'paid' ? GREEN : RED
}

/** True when a lesson is a future occurrence generated by a recurring schedule. */
export function isScheduleOccurrence(lesson: Lesson): boolean {
  return lesson.schedule_id != null && lesson.status === 'scheduled'
}
